name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install deps
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Basic check
      - name: Run basic check
        run: python -c "import fastapi"

      # -----------------------
      # 🐳 Docker Steps
      # -----------------------

      # 5. Build image
      - name: Build Docker image
        run: docker build -t fastapi-app .

      # 6. Run container
      - name: Run container
        run: docker run -d -p 8000:8000 fastapi-app

      # 7. Wait for server
      - name: Wait for app
        run: sleep 10

      # 8. Debug (VERY IMPORTANT)
      - name: Check running containers
        run: docker ps

      # 9. Test API
      - name: Test API
        run: curl --fail http://localhost:8000



# name: CI Pipeline

# on:
#   push:
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt

#       - name: Run basic check
#         run: |
#           python -c "import fastapi"